// This file is a placeholder. Replace with your actual firebase_options.dart
// generated by: flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCql84rEXmGSqQnWvoZh8TmXZcvq77y-Ns',
    appId: '1:131350284305:android:1ab7d2d76577ad871c09b0',
    messagingSenderId: '131350284305',
    projectId: 'noor-school-55240',
    storageBucket: 'noor-school-55240.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaEt7mmZuhfZdNO9M3210cgm5mS7sXvhY',
    appId: '1:131350284305:ios:2ae79a61eafe41471c09b0',
    messagingSenderId: '131350284305',
    projectId: 'noor-school-55240',
    storageBucket: 'noor-school-55240.firebasestorage.app',
    iosBundleId: 'com.school.noor',
  );
}
