// This file is a placeholder. Replace with your actual firebase_options.dart
// generated by: flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJHJHlfpOBZrmrjnyJ4HXXeEeHt5yjvw0',
    appId: '1:998389060248:android:be3243e958710228c676ed',
    messagingSenderId: '998389060248',
    projectId: 'noor-9754e',
    storageBucket: 'noor-9754e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaERBcBlTr3gg0BhT0LHiFqjUN1heiZPw',
    appId: '1:998389060248:ios:d41a33a164400408c676ed',
    messagingSenderId: '998389060248',
    projectId: 'noor-9754e',
    storageBucket: 'noor-9754e.firebasestorage.app',
    iosBundleId: 'com.school.noor',
  );
}
